version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.09

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker build -t app . --progress=plain
